### ISSUE TITLE
Take out all matching ticker symbols between the list and string (article)

### ISSUE THREAD

**Issue by kris524** [kris524/Stock-Market-Project#2]
The Find all symbols.py script takes out individual letters of matching elements, but we need the full symbol name

**Comment by BongumusaSizwe** [comment]
Where is the file Yahoo.csv?

**Comment by kris524** [comment]
Sorry!! I forgot to add it! Here it is
[Yahoo data.xlsx](https://github.com/kris524/Stock-Market-Project/files/6758269/Yahoo.data.xlsx)

**Comment by kris524** [comment]
Sorry, I forgot to add it! I have added it now

**Comment by kris524** [comment]
This is my latest work, I iterate over each word and I append it to a list.  Then I plan on comparing article_list with the symbols list but the ticker symbols are inside brackets and it doesn't recognize them like (TSLA), (GS), etc and Im not sure how to proceed :(
`article_list =[]
for word in article.split():
    article_list.append(word)
print(article_list)`

**Comment by BongumusaSizwe** [comment]
Do this after splitting:

`
words = article.split()
#Remove any punctuation in words
for i in range(len(words)):
    words[i] = ''.join(e for e in words[i] if e.isalnum())
#Use the AND operator to select elements common to the two lists
article_tickers = set(words)&set(symbols)
`

**Comment by kris524** [comment]
Yes, it works. Also, since (0175.HK and  VOW3.DE are needed but are missing. What I did is I updated the data and removed all dots (.) from Yahoo data as well. Now it works even better thanks to you :)
